### ISSUE TITLE
support gevent 20.x: new hub destruction incompatible with gipc's child handler approach

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#103]
After https://github.com/gevent/gevent/pull/1604/ it seems to be the case that https://github.com/jgehrcke/gipc/blob/c8125872fa263f93e920f3041cac2d51063c614c/gipc/gipc.py#L344 may hang indefinitely in https://github.com/gevent/gevent/pull/1604/files#diff-94cf0d2f0e2386d3392cf0e1908536efR766.

Added two print statements:
```
792         # things will go VERY, VERY wrong.
793         print("destroy: PRE THROW")
794         try:
795             self.throw(GreenletExit)
796             print('AFTER THROW')
797         except LoopExit:
798             # Expected.
```

During execution of ` pytest --log-level=debug -vvv -s -k childchild
` the last thing we see is
```
16:39:38,932.5  [22187]_child# Destroy hub and default loop.
destroy: PRE THROW
^CKeyboardInterrupt
```

**Comment by TylerWilley** [comment]
hub.destroy hanging is fixed in gevent 20.12.1, using gipc 1.1.1 seems to work for our app with 20.12.1.

I'm curious if there are other outstanding compatibility issues that need to be resolved with gipc before using it there, I pulled the gevent update branch and pushed it to our local pip repository and it hasn't had trouble thus far.

**Comment by jgehrcke** [comment]
@TylerWilley I had another look. There are tests in gipc's test suite that make a child process crash when it exercises https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/hub.py#L807 -- from here, things are a little more challenging to debug: I assume that the crash happens somewhere around https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/libev/corecext.pyx#L576.

**Comment by u2takey** [comment]
> @TylerWilley I had another look. With gevent 21.1, there are tests in gipc's test suite that make a child process crash when it exercises https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/hub.py#L807 -- from here, things are a little more challenging to debug: I assume that the crash happens somewhere around https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/libev/corecext.pyx#L576.

any update on the compatibility issue?

**Comment by TylerWilley** [comment]
I posted a PR that fixes the unit tests here: https://github.com/jgehrcke/gipc/pull/110

It relies on forcing python3.8 from using `spawn` as the default back to `fork` to preserve how gipc passes file descriptors, and makes use of gevent's reinit method instead of the dirty cleanup it was doing before.

Tested it on python 3.6.9 + gevent 1.2.2 and 3.8.6 + gevent 20.12.1

**Comment by u2takey** [comment]
I use gipc with multiprocess.queue, after upgrade gevent to 20.x, program broken.
errors:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 328, in _exit_function
    p.join()
  File "/ib/python2.7/site-packages/gipc/gipc.py", line 590, in join
    self._returnevent.wait(timeout)
  File "src/gevent/event.py", line 127, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
error: cannot switch to a different thread
Error in sys.exitfunc:
```
