### ISSUE TITLE
gunicorn+gevent-websocket setup fails on ubuntu

### ISSUE THREAD

**Issue by noamgat** [jgehrcke/gipc#115]
Hi,

I'm trying to setup the following server structure:
gunicorn + flask-socketio + gevent-websocket + gipc:
Users can connect in websockets. Each websocket spawns a worker process that does the heavy processing, and puts the results via pipes. I followed the example code from the benchmark test, in which I spawn two pipe sets - one for communicating requests from the parent to the child, and another for communicating results from the child to the parent.

I can't post the whole app structure, but the interesting snippets are:
The parent process:
```
requests_reader, requests_writer = gipc.pipe()
        results_reader, results_writer = gipc.pipe()
        self.log_queue = multiprocessing.Queue()
        process_args = (profile_id, is_prod, requests_reader, results_writer, self.log_queue, logging.root.level)
        self.requests_writer = requests_writer
        self.results_reader = results_reader
        self.worker_process = gipc.start_process(MySubProcess._worker_process_method,
                                                 process_args,
                                                 name=f'EditSession{profile_id}')
```

The child process method:

```
 @staticmethod
    def _worker_process_method(profile_id, is_prod, requests_reader, results_writer, log_queue, log_level):
        launch_or_reset_subprocess_logger(log_queue, log_level=log_level, job_id=f'ED_{profile_id}')
        while True:
            next_request = requests_reader.get()
```

On windows, this works.
However, on ubuntu, this fails with the following logs:

```
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] Invoke target `<function EditResultSessionProcess._worker_process_method at 0x7fc5533a1ef0>` in child process.
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] SIGCHLD watcher for 3484006 started.
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] Invalidate <_GIPCReader_f665aa fd: 16> in parent.
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] Invalidating <_GIPCReader_f665aa fd: 16> ...
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] Invalidate <_GIPCWriter_e6b76a fd: 19> in parent.
[2021-07-08 16:32:58 +0000] [3483869] [DEBUG] Invalidating <_GIPCWriter_e6b76a fd: 19> ...
Process EditSession16796:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/site-packages/gipc/gipc.py", line 393, in _child
    target(*args, **kwargs)
  File "/home/ubuntu/server_demo/server.py", line 103, in _worker_process_method
    next_request = requests_reader.get()
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/site-packages/gipc/gipc.py", line 982, in get
    msize, = struct.unpack("!i", self._recv_in_buffer(4).getvalue())
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/site-packages/gipc/gipc.py", line 932, in _recv_in_buffer
    chunk = _read_nonblocking(self._fd, remaining)
  File "/home/ubuntu/miniconda3/envs/pythonenv/lib/python3.7/site-packages/gevent/os.py", line 100, in nb_read
    result = _read(fd, n)
OSError: [Errno 9] Bad file descriptor
```

The "invalidating xxx" lines are good, and also happen on windows, they are the ones that mean that once a pipe has been passed to a child process, the parent can no longer put/get from it.
Does this ring any bells on why it would work on windows and fail on linux (ubuntu)?

**Comment by noamgat** [comment]
This script fails in linux, but only if the multiprocess method is set to spawn:
```
import io
import logging
import multiprocessing

try:
    multiprocessing.set_start_method('spawn')
except:
    pass

import traceback

import gipc


def _example_worker_process_method(profile_id, is_prod, requests_reader, results_writer, log_queue, log_level):
    while True:
        next_request = requests_reader.get()
        request_type = next_request['type']
        params = next_request.get('params', None)
        try:
            if request_type == 'edit':
                new_results = 2
                results_writer.put(new_results)
        except Exception as e:
            # https://jichu4n.com/posts/python-multiprocessing-and-exceptions/
            exc_buffer = io.StringIO()
            traceback.print_exc(file=exc_buffer)
            logging.error(f'an exception occurred in editor sub-process: {exc_buffer.getvalue()}')
            results_writer.put(e)


if __name__ == '__main__':
    logging.basicConfig()
    requests_reader, requests_writer = gipc.pipe()
    results_reader, results_writer = gipc.pipe()
    log_queue = multiprocessing.Queue()
    profile_id = 10
    is_prod = False
    process_args = (profile_id, is_prod, requests_reader, results_writer, log_queue, logging.root.level)
    requests_writer = requests_writer
    results_reader = results_reader
    worker_process = gipc.start_process(_example_worker_process_method, process_args, name=f'EditSession{profile_id}')
    requests_writer.put({'type': 'edit', 'params': None})
    result = results_reader.get()
    print(result)
    print("DONE")
```

**Comment by noamgat** [comment]
It appears that this is related to an issue that was solved on master branch, and is solved on master.
Is there a timeline for the next release?

**Comment by jgehrcke** [comment]
> It appears that this is related to an issue that was solved on master branch, and is solved on master. Is there a timeline for the next release?

Thanks for asking and therefore accelerating that timeline :) I've been rather busy recently, sorry for the delay.

Can you confirm that the head of the master branch works for you? I think this should install that:
```
pip install git+https://github.com/jgehrcke/gipc
```

**Comment by jgehrcke** [comment]
I just released https://pypi.org/project/gipc/1.3.0/ -- can you give this a shot?

**Comment by noamgat** [comment]
Works!
