### ISSUE TITLE
Can't set child process as data producer and parent process(with gevent) as data consumer?

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#20]
Originally reported by: **Cherrot Luo (Bitbucket: [cherrot](https://bitbucket.org/cherrot), GitHub: [cherrot](https://github.com/cherrot))**

----------------------------------------

The following is my code, it looks like simply exchanging the reader and writer of Example 1.  However, the KeyboardIntterupt would cause EOFError.

```
#!python

import gevent                  
import gipc                    
                               
                               
def main():                    
    with gipc.pipe() as (r, w): 
        p = gipc.start_process(target=process, args=(w, ))
        wg = gevent.spawn(worker, r)
        try:                   
            p.join()           
        except KeyboardInterrupt:
            p.terminate()      
            p.join()           
        wg.kill()          
                               
                               
def worker(pipe):              
    while True:                
        print "Got from pipe: '%s'" % pipe.get()
                               
                               
def process(pipe):             
    while True:            
        pipe.put("written to pipe")
        gevent.sleep(1)    
                               
                               
if __name__ == "__main__":     
    main()
```

The following is the output:

```
#!shell

python test.py 
Got from pipe: 'written to pipe'
Got from pipe: 'written to pipe'
Got from pipe: 'written to pipe'
^CKeyboardInterrupt
Traceback (most recent call last):
  File "PATH/TO/lib/python2.7/site-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "test.py", line 25, in worker
    print "Got from pipe: '%s'" % pipe.get()
  File "PATH/TO/lib/python2.7/site-packages/gipc/gipc.py", line 855, in get
    msize, = struct.unpack("!i", self._recv_in_buffer(4).getvalue())
  File "PATH/TO/lib/python2.7/site-packages/gipc/gipc.py", line 810, in _recv_in_buffer
    "Most likely, the other pipe end is closed.")
EOFError: Most likely, the other pipe end is closed.
<Greenlet at 0x7f07b00bb4b0: worker(<_GIPCReader_f06b91 fd: 3>)> failed with EOFError
```

----------------------------------------
- Bitbucket: https://bitbucket.org/jgehrcke/gipc/issue/20

**Comment by jgehrcke** [comment]
@cherrot this is expected. With `p.terminate()` you send a SIGTERM to the child process as of which it terminates. That also means that the write end of the pipe is being closed. The reader in your parent process sees and reports exactly that: `EOFError: Most likely, the other pipe end is closed.`.
