### ISSUE TITLE
[Windows] time-synchronization example fails on Windows with gevent 1.1

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#21]
Originally reported by: **Kevin Smyth (Bitbucket: [kevinsmyth](https://bitbucket.org/kevinsmyth), GitHub: Unknown)**

----------------------------------------

Python 2.7.10 x86 on Windows 10 in virtual environment "gipc":

`pip install gipc==0.6.0 gevent==1.0.2 greenlet==0.4.10`

gevent 1.0.2:

```
(gipc) C:\Users\kevin\Downloads>python gipc_test.py
2016-06-28 15:08:38,069 DEBUG Invoke target `<function writer_process at 0x0298DC70>` in child process.
2016-06-28 15:08:38,073 DEBUG Invalidate <_GIPCWriter_3a5054 fd: None> in parent.
2016-06-28 15:08:38,075 DEBUG Invalidating <_GIPCWriter_3a5054 fd: 3> ...
2016-06-28 15:08:38,075 DEBUG Invalidate <_GIPCReader_47e648 fd: None> in parent.
2016-06-28 15:08:38,075 DEBUG Invalidating <_GIPCReader_47e648 fd: 3> ...
2016-06-28 15:08:38,118 DEBUG _child start. target: `<function writer_process at 0x029F1EF0>`
2016-06-28 15:08:38,118 DEBUG Legitimate <_GIPCWriter_3a5054 fd: None> for current process.
2016-06-28 15:08:38,119 DEBUG Handle `<_GIPCWriter_3a5054 fd: 4>` is now valid in child.
2016-06-28 15:08:38,119 DEBUG Legitimate <_GIPCReader_47e648 fd: None> for current process.
2016-06-28 15:08:38,119 DEBUG Handle `<_GIPCReader_47e648 fd: 5>` is now valid in child.
2016-06-28 15:08:38,125 DEBUG Invalidating <_GIPCWriter_3a5054 fd: 4> ...
2016-06-28 15:08:38,125 DEBUG Invalidating <_GIPCReader_47e648 fd: 5> ...
Time delta: 0.00000000 s.
2016-06-28 15:08:38,135 DEBUG Invalidating <_GIPCWriter_ddaadf fd: 4> ...
2016-06-28 15:08:38,137 DEBUG Invalidating <_GIPCReader_56dd98 fd: 5> ...
```

`pip install gipc==0.6.0 gevent==1.1.1 greenlet==0.4.10`

gevent 1.1.1:

```
(gipc) C:\Users\kevin\Downloads>python gipc_test.py
2016-06-28 15:08:18,006 DEBUG Invoke target `<function writer_process at 0x029661B0>` in child process.
2016-06-28 15:08:18,009 DEBUG Invalidate <_GIPCWriter_7ac2f9 fd: None> in parent.
2016-06-28 15:08:18,010 DEBUG Invalidating <_GIPCWriter_7ac2f9 fd: 3> ...
2016-06-28 15:08:18,010 DEBUG Invalidate <_GIPCReader_b935fe fd: None> in parent.
2016-06-28 15:08:18,010 DEBUG Invalidating <_GIPCReader_b935fe fd: 3> ...
2016-06-28 15:08:18,058 DEBUG _child start. target: `<function writer_process at 0x02E0D430>`
2016-06-28 15:08:18,059 DEBUG Legitimate <_GIPCWriter_7ac2f9 fd: None> for current process.
2016-06-28 15:08:18,059 DEBUG Handle `<_GIPCWriter_7ac2f9 fd: 4>` is now valid in child.
2016-06-28 15:08:18,059 DEBUG Legitimate <_GIPCReader_b935fe fd: None> for current process.
2016-06-28 15:08:18,059 DEBUG Handle `<_GIPCReader_b935fe fd: 5>` is now valid in child.
Process _GProcess-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\Lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kevin\Downloads\gipc\lib\site-packages\gipc\gipc.py", line 361, in _child
    target(*args, **kwargs)
  File "C:\Users\kevin\Downloads\gipc_test.py", line 29, in writer_process
    cend.put(time.time())
  File "C:\Users\kevin\Downloads\gipc\lib\site-packages\gipc\gipc.py", line 953, in __exit__
    self[0].__exit__(exc_type, exc_value, traceback)
  File "C:\Users\kevin\Downloads\gipc\lib\site-packages\gipc\gipc.py", line 765, in __exit__
    "operation out of context." % self))
GIPCLocked: Context manager can't close handle <_GIPCReader_b935fe fd: 5>. It's
locked for I/O operation out of context.
2016-06-28 15:08:18,065 DEBUG Invalidating <_GIPCWriter_2c9b8a fd: 4> ...
2016-06-28 15:08:18,065 DEBUG Invalidating <_GIPCReader_5b828e fd: 5> ...
Traceback (most recent call last):
  File "gipc_test.py", line 33, in <module>
    main()
  File "gipc_test.py", line 16, in main
    assert pend.get() == "ACK"
  File "C:\Users\kevin\Downloads\gipc\lib\site-packages\gipc\gipc.py", line 855, in get
    msize, = struct.unpack("!i", self._recv_in_buffer(4).getvalue())
  File "C:\Users\kevin\Downloads\gipc\lib\site-packages\gipc\gipc.py", line 810, in _recv_in_buffer
    "Most likely, the other pipe end is closed.")
EOFError: Most likely, the other pipe end is closed.
```

----------------------------------------
- Bitbucket: https://bitbucket.org/jgehrcke/gipc/issue/21

**Comment by jgehrcke** [comment]
In current `master` the `synchronization.py` example passes on Windows with gevent 1.3.6 and CPython 3.6.x. I consider this fixed but will keep this open until we have a release.
