### ISSUE TITLE
Support PyPy

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#23]
Originally reported by: **Heungsub Lee (Bitbucket: [sublee](https://bitbucket.org/sublee), GitHub: [sublee](https://github.com/sublee))**

----------------------------------------

Do you have any plan to support PyPy?  Now `gipc` fails on PyPy with `ImportError`:

```python
>>>> import gipc                                                                        
Traceback (most recent call last):                                                      
  File "<stdin>", line 1, in <module>                                                   
  File "/home/sub/env-pypy/site-packages/gipc/__init__.py", line 8, in <module>         
    from .gipc import pipe, start_process, GIPCError, GIPCClosed, GIPCLocked            
  File "/home/sub/env-pypy/site-packages/gipc/gipc.py", line 29, in <module>            
    import multiprocessing.reduction                                                    
  File "/usr/lib/pypy/lib-python/2.7/multiprocessing/reduction.py", line 55, in <module>
    raise ImportError('pickling of connections not supported')                          
ImportError: pickling of connections not supported                                      
```

Maybe `multiprocessing.reduction` is required only for Windows.  If so, how about we make some failover to this `ImportError`?

----------------------------------------
- Bitbucket: https://bitbucket.org/jgehrcke/gipc/issue/23

**Comment by jgehrcke** [comment]
I am reasonably confident that `master` "supports" PyPy now. The test suite passes. The example programs execute. There is a performance issue I think, but it might not be relevant for many use cases. I will close this issue with the next release of gipc.

CC @sublee @olliemath @zannen
