### ISSUE TITLE
Example `serverclient.py` fails with `No module named platform` on MacOS with Python 2.7.15

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#51]
```
+python serverclient.py

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
  File "src/gevent/greenlet.py", line 700, in gevent._greenlet.Greenlet._report_error
  File "/usr/local/lib/python2.7/site-packages/gevent/_tblib.py", line 371, in g
  File "/usr/local/lib/python2.7/site-packages/gevent/_tblib.py", line 425, in dump_traceback
  File "/usr/local/lib/python2.7/site-packages/gevent/_tblib.py", line 402, in _init
ImportError: No module named platform
2018-09-29T12:37:06Z <callback at 0x10b708320 stopped> failed with ImportError
```

**Comment by jgehrcke** [comment]
This happened with system Python on macOS. I have not seen that when building CPython (via pyenv).

**Comment by jgehrcke** [comment]
Do we want to support system Python on macOS? First step: build a CI check dedicated to that. Could even be that this passes now with the recent workarounds for macOS.

**Comment by jgehrcke** [comment]
We're testing with system Python now on Mac OS: https://github.com/jgehrcke/gipc/blob/c9fa60d234dc04a92f136274eb59539a33ec291b/.travis.yml#L112

It works. Closing.
