### ISSUE TITLE
Example serverclient.py fails with 'Too many open files' on MacOS

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#56]
[181003_gipc_serverclient_too_many_open_files_macos.txt](https://github.com/jgehrcke/gipc/files/2439925/181003_gipc_serverclient_too_many_open_files_macos.txt)

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "serverclient.py", line 63, in client
  File "/Users/travis/ve-pyenv-3.6.6/lib/python3.6/site-packages/gevent/_socket3.py", line 100, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by jgehrcke** [comment]
Fixed via #57.
