### ISSUE TITLE
CI failure: pytest: attrib() got an unexpected keyword argument 'convert'

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#87]
See https://travis-ci.org/jgehrcke/gipc/builds/597149803

```
++pytest -vv test/
Traceback (most recent call last):
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/config/__init__https://travis-ci.org/jgehrcke/gipc/builds/597149803.py", line 153, in get_config
    pluginmanager.import_plugin(spec)
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/config/__init__.py", line 522, in import_plugin
    __import__(importspec)
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "/home/travis/ve-pyenv-pypy3.5-6.0.0/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by jgehrcke** [comment]
Discussed here: https://stackoverflow.com/a/58189684
